package lexfo.scalpel;

import java.awt.*;
import java.io.File;
import javax.swing.*;
import javax.swing.border.TitledBorder;

public class ConfigTab extends JFrame {

	private JPanel panel1;
	private JButton browseButton;
	private JTextField textField1;
	private JPanel browsePanel;
	private ScalpelExecutor executor;

	public ConfigTab(ScalpelExecutor executor, String defaultPath) {
		this.executor = executor;
		setContentPane(panel1);
		setVisible(true);
		setScriptPath(defaultPath);
		// Handle browse button click.
		browseButton.addActionListener(e -> {
			final JFileChooser fileChooser = new JFileChooser();
			fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

			// Set default path to the path in the text field.
			fileChooser.setCurrentDirectory(new File(textField1.getText()));

			int result = fileChooser.showOpenDialog(this);
			if (result == JFileChooser.APPROVE_OPTION) {
				setScriptPath(fileChooser.getSelectedFile().getAbsolutePath());
			}
		});
	}

	private void setScriptPath(String path) {
		executor.setScript(path);
		textField1.setText(path);
	}

	public ConfigTab(ScalpelExecutor executor) {
		this(executor, "");
	}

	public Component uiComponent() {
		return panel1;
	}

	{
		// GUI initializer generated by IntelliJ IDEA GUI Designer
		// >>> IMPORTANT!! <<<
		// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel1 = new JPanel();
		panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), 10, 10));
		panel1.setBorder(
			BorderFactory.createTitledBorder(
				null,
				"",
				TitledBorder.DEFAULT_JUSTIFICATION,
				TitledBorder.DEFAULT_POSITION,
				null,
				null
			)
		);
		browsePanel = new JPanel();
		browsePanel.setLayout(
			new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(10, 10, 10, 10), 10, -1)
		);
		browsePanel.setBackground(new Color(-5198676));
		panel1.add(
			browsePanel,
			new com.intellij.uiDesigner.core.GridConstraints(
				0,
				0,
				1,
				1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK |
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK |
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
				null,
				null,
				null,
				0,
				false
			)
		);
		browseButton = new JButton();
		browseButton.setText("Browse");
		browsePanel.add(
			browseButton,
			new com.intellij.uiDesigner.core.GridConstraints(
				0,
				0,
				1,
				1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK |
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				null,
				null,
				null,
				1,
				false
			)
		);
		textField1 = new JTextField();
		textField1.setText("");
		browsePanel.add(
			textField1,
			new com.intellij.uiDesigner.core.GridConstraints(
				0,
				1,
				1,
				1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
				com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
				null,
				new Dimension(400, -1),
				null,
				0,
				false
			)
		);
		final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
		browsePanel.add(
			spacer1,
			new com.intellij.uiDesigner.core.GridConstraints(
				0,
				2,
				1,
				1,
				com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
				com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
				com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
				1,
				null,
				null,
				null,
				0,
				false
			)
		);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel1;
	}
}
